---
rules:
  github-env:
    ignore:
      - action.yml:15:7
      - action.yml:22:7
      - action.yml:43:7
      - action.yml:48:7
  unpinned-images:
    ignore:
      - ci_container.yml:23:7
  unpinned-uses:
    ignore:
      - ci.yml:45:9
      - ci_container.yml:50:9
