---
name: try Python platform module

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:

jobs:
  run-python-platform:
    name: os:${{ matrix.os }} / version:${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-13
          - macos-14
          - ubuntu-22.04
          - windows-latest
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - '3.10'
          - 3.11
          - 3.12
        exclude:
          - os: macos-14
            python-version: 3.7
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: set JSON output file location (Windows)
        run: |
          Add-Content -Path "${env:GITHUB_ENV}" -Value "TRY_PLATFORM_OUTPUTFILE=${{ github.workflow }}_${{ github.run_id }}_${{ github.run_attempt }}.json"
        if: ${{ matrix.os == 'windows-latest' }}
      - name: set JSON output file location (Unix)
        run: |
          echo "TRY_PLATFORM_OUTPUTFILE=${{ github.workflow }}_${{ github.run_id }}_${{ github.run_attempt }}.json" >> "${GITHUB_ENV}"
        if: ${{ matrix.os != 'windows-latest' }}
      - name: try calling platform code
        run: |
          python try_platform.py
      - name: save JSON output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.workflow }}_${{ github.run_id }}_${{ github.run_attempt }}
          path: '*.json'
