---
name: try Python platform module

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

permissions: {}

jobs:
  run-python-platform:
    name: os:${{ matrix.os }} / version:${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    env:
      JOB_NAME_DIRTY: ${{ matrix.os }}_${{ matrix.python-version }}
    strategy:
      matrix:
        os:
          # - macos-13
          - macos-14
          # - ubuntu-22.04
          - windows-latest
        python-version:
          - 3.7
          # - 3.8
          # - 3.9
          # - '3.10'
          # - 3.11
          # - 3.12
          - 3.13
        exclude:
          - os: macos-14
            python-version: 3.7
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: berquist/try-python-platform@combined-ci
        with:
          use-sudo: true
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
